### ISSUE TITLE
Third parameter still not working properly

### ISSUE THREAD

**Issue by iimog** [ugexe/Text--Levenshtein--XS#11]
Now using version 0.501 of ```Text::Levenshtein::XS``` from ```CPAN```.
The fix for #10 leads to the correct result when using:
```{perl}
distance('ACGTAG', 'AGTAG', 2) # returns 1 
```
But if the cut-off is the same as the result the bug still occurs:
```{perl}
distance('ACGTAG', 'AGTAG', 1) # should be 1 is undef 
```

**Comment by ugexe** [comment]
Thanks. Corrected in https://github.com/ugexe/Text--Levenshtein--XS/commit/a4142bd526e295cae875145f99928f0cff793659 or on cpan as v0.502 :)

**Comment by iimog** [comment]
Wonderful, thanks a lot!
